import ast
import difflib
import json
import logging
import os
import re
from uuid import uuid4

logger = logging.getLogger(__name__)

from openenv.core.env_server.interfaces import Environment
from openenv.core.env_server.types import State

try:
    from ..models import LegacyforgeAction, LegacyforgeObservation
except ImportError:
    from models import LegacyforgeAction, LegacyforgeObservation  # type: ignore

try:
    from .sandbox import run_in_sandbox
    from .triangle_of_truth import validate_test
except ImportError:
    from sandbox import run_in_sandbox  # type: ignore
    from triangle_of_truth import validate_test  # type: ignore

# ---------------------------------------------------------------------------
# FastAPI documentation snippets for read_docs()
# ---------------------------------------------------------------------------
DOCS_SNIPPETS = {
    "routing": """\
FastAPI Routing:
  @app.get("/items/{item_id}")
  async def read_item(item_id: int):
      return {"item_id": item_id}

Path parameters are declared directly in the function signature.
Use async def for all endpoints in FastAPI.""",

    "pydantic": """\
Pydantic Response Models:
  from pydantic import BaseModel

  class ItemResponse(BaseModel):
      item_id: int
      name: str

  @app.get("/items/{item_id}", response_model=ItemResponse)
  async def read_item(item_id: int):
      return ItemResponse(item_id=item_id, name="example")

Always declare a response_model to validate and document your API output.""",

    "async": """\
Async Endpoints in FastAPI:
  # WRONG (Flask style):
  def get_item(item_id: int):
      return {"item_id": item_id}

  # CORRECT (FastAPI style):
  async def get_item(item_id: int):
      return {"item_id": item_id}

Use `async def` for all FastAPI endpoints to enable non-blocking IO.""",

    "background_tasks": """\
FastAPI Background Tasks:
  from fastapi import BackgroundTasks

  def write_log(message: str):
      with open("log.txt", "a") as f:
          f.write(message)

  @app.post("/send/")
  async def send_notification(background_tasks: BackgroundTasks):
      background_tasks.add_task(write_log, "notification sent")
      return {"message": "Notification sent"}""",

    "lifespan": """\
FastAPI Lifespan (startup/shutdown):
  from contextlib import asynccontextmanager

  @asynccontextmanager
  async def lifespan(app: FastAPI):
      # Startup logic
      print("Starting up...")
      yield
      # Shutdown logic
      print("Shutting down...")

  app = FastAPI(lifespan=lifespan)

Never use deprecated @app.on_event("startup") in modern FastAPI.""",

    "exceptions": """\
FastAPI Exception Handling:
  from fastapi import HTTPException

  @app.get("/items/{item_id}")
  async def read_item(item_id: int):
      if item_id <= 0:
          raise HTTPException(status_code=404, detail="Item not found")
      return {"item_id": item_id}

Always raise HTTPException with the correct status_code.
404 = Not Found, 422 = Validation Error, 400 = Bad Request.""",
}

# ---------------------------------------------------------------------------
# Level 1 initial Flask code (the "working code" the agent starts with)
# ---------------------------------------------------------------------------
_LEVEL1_INITIAL_CODE = """\
from flask import Flask, jsonify

app = Flask(__name__)

@app.route('/items/<int:item_id>', methods=['GET'])
def read_item(item_id):
    if item_id > 0:
        return {"item_id": item_id, "name": "Test Item"}
    return {"error": "Item not found"}, 404

if __name__ == "__main__":
    app.run()
"""

# Level 1 test file path (used by run_tests)
_LEVEL1_TESTS_PATH = os.path.join(os.path.dirname(__file__), "levels", "level1_tests.py")

# Path to the offline docs cache generated by host_cache_builder.py
_DOCS_CACHE_PATH = os.path.join(os.path.dirname(__file__), "static_docs_cache.json")


# ---------------------------------------------------------------------------
# HistoryAggregator
# ---------------------------------------------------------------------------
class HistoryAggregator:
    def __init__(self):
        self.async_errors = 0
        self.pydantic_errors = 0
        self.route_errors = 0
        self.middleware_errors = 0
        self.lifespan_errors = 0

    def update_from_output(self, output: str):
        """Parse pytest output and categorise failures into buckets."""
        text = output.lower()
        if "async" in text or "coroutine" in text:
            self.async_errors += 1
        if "pydantic" in text or "validationerror" in text or "response_model" in text:
            self.pydantic_errors += 1
        if "404" in text or "422" in text or "route" in text or "url" in text:
            self.route_errors += 1
        if "middleware" in text:
            self.middleware_errors += 1
        if "lifespan" in text or "startup" in text or "shutdown" in text:
            self.lifespan_errors += 1


# _StrategyTracker removed — strategy scoring is computed inline in step() at done-time


# ---------------------------------------------------------------------------
# Main environment
# ---------------------------------------------------------------------------
class LegacyforgeEnvironment(Environment):
    SUPPORTS_CONCURRENT_SESSIONS: bool = True

    # -----------------------------------------------------------------------
    def __init__(self):
        self._state = State(episode_id=str(uuid4()), step_count=0)
        # Load offline docs cache — fall back to empty dict if not yet generated
        self._docs_cache: dict[str, str] = {}
        try:
            with open(_DOCS_CACHE_PATH, "r", encoding="utf-8") as fh:
                self._docs_cache = json.load(fh)
            logger.info("Loaded %d docs cache entries from %s",
                        len(self._docs_cache), _DOCS_CACHE_PATH)
        except FileNotFoundError:
            logger.warning(
                "static_docs_cache.json not found at %s. "
                "Run server/host_cache_builder.py to generate it. "
                "Falling back to hardcoded DOCS_SNIPPETS.",
                _DOCS_CACHE_PATH,
            )
        self._init_episode()

    def _init_episode(self):
        self.episode_log = []
        self.history = HistoryAggregator()
        self.current_level = 1
        self.phase = 1
        self.test_suite_size = 6          # 6 tests in level1_tests.py
        self.challenger_win_rate = 0.0
        self.test_passage_rate = 0.0
        self.working_code = _LEVEL1_INITIAL_CODE
        
        self.read_docs_count = 0
        self.edit_count = 0
        self.run_tests_count = 0
        self.code_review_count = 0
        self.last_action = None
        self.last_passage_rate = 0.0
        self.passage_milestones_hit = set()
        self.edited_since_last_test = False
        self.read_docs_before_first_edit = False
        self.run_tests_after_every_edit = True
        self.submit_before_phase2 = False

    # -----------------------------------------------------------------------
    def reset(self, level=None) -> LegacyforgeObservation:
        self._state = State(episode_id=str(uuid4()), step_count=0)
        self._init_episode()
        self.current_level = level if level is not None else 1

        obs_dict = self._build_obs_dict("Initial state — migrate Flask code to FastAPI")
        return LegacyforgeObservation(
            **obs_dict,
            observation=obs_dict,
            reward_breakdown={"migration_success": 0.0, "strategy_quality": 0.0,
                              "adversarial_bonus": 0.0, "oracle_penalty": 0.0,
                              "progress_bonus": 0.0},
            done=False,
            reward=0.0,
            info={"phase": self.phase},
        )

    # -----------------------------------------------------------------------
    def step(self, action: LegacyforgeAction) -> LegacyforgeObservation:  # type: ignore[override]
        self._state.step_count += 1
        action_type = action.action_type
        self.last_action = action_type
        reward = 0.0
        done = False
        info: dict = {}
        
        # Step-local breakdown components
        progress_bonus = 0.0
        migration_success_reward = 0.0
        adversarial_bonus = 0.0
        oracle_penalty = 0.0

        if action_type == "read_docs":
            self.read_docs_count += 1
            if self.read_docs_count <= 2:
                reward = 0.0
            else:
                reward = -0.5
            if self.edit_count == 0:
                self.read_docs_before_first_edit = True
            
            # call handler just for info/summary
            _, summary, info = self._handle_read_docs(action)

        elif action_type == "edit_function":
            self.edit_count += 1
            self.edited_since_last_test = True
            
            _, summary, info = self._handle_edit_function(action)
            
            if info.get("compile_ok"):
                # FIX ISSUE 1: no double-penalty — step reward is 0.2 if docs read, else 0.0
                # strategy_score at episode-end still penalises skipping docs
                reward = 0.2 if self.read_docs_count > 0 else 0.0
            else:
                reward = -0.5
                
            self.run_tests_after_every_edit = False

        elif action_type == "run_tests":
            if not self.edited_since_last_test:
                # BUG 2 FIX: still count the attempt even when no edits preceded it
                reward = -0.5
                self.run_tests_count += 1
                summary = "run_tests called without any edits"
            else:
                with open(_LEVEL1_TESTS_PATH, "r") as f:
                    test_code = f.read()

                result = run_in_sandbox(self.working_code, test_code)

                # Determine if the sandbox actually produced parseable results
                sandbox_ok = not result["timed_out"] and not (
                    not result["passed"] and "SyntaxError" in result.get("error", "")
                )

                if result["timed_out"]:
                    reward = -1.0
                    self.test_passage_rate = 0.0
                elif not sandbox_ok:
                    # Hard failure (SyntaxError or compile crash)
                    reward = -0.5
                    self.test_passage_rate = 0.0
                else:
                    output = result["output"]
                    passed_match = re.search(r"(\d+) passed", output)
                    failed_match = re.search(r"(\d+) failed", output)
                    passed = int(passed_match.group(1)) if passed_match else (3 if result["passed"] else 0)
                    failed = int(failed_match.group(1)) if failed_match else (0 if result["passed"] else 3)
                    total_tests = passed + failed or self.test_suite_size

                    reward = passed * 0.5 - failed * 0.2
                    migration_success_reward = reward

                    self.test_passage_rate = passed / total_tests
                    self.history.update_from_output(output + result.get("error", ""))

                    # BUG 1 FIX: milestone bonuses only on a successful sandbox run
                    if self.test_passage_rate >= 0.33 and "33" not in self.passage_milestones_hit:
                        progress_bonus += 0.5
                        self.passage_milestones_hit.add("33")
                    if self.test_passage_rate >= 0.67 and "67" not in self.passage_milestones_hit:
                        progress_bonus += 0.5
                        self.passage_milestones_hit.add("67")
                    if self.test_passage_rate >= 1.00 and "100" not in self.passage_milestones_hit:
                        progress_bonus += 1.0
                        self.passage_milestones_hit.add("100")

                    if self.test_passage_rate >= 0.70 and self.phase == 1:
                        self.phase = 2
                        progress_bonus += 1.0

                    reward += progress_bonus

                self.edited_since_last_test = False
                self.run_tests_after_every_edit = True
                self.run_tests_count += 1
                summary = f"run_tests: passage={self.test_passage_rate:.2f}"
                info.update({
                    "passed": result.get("passed", False),
                    "timed_out": result.get("timed_out", False),
                    "test_passage_rate": self.test_passage_rate,
                    "phase": self.phase,
                })

        elif action_type == "code_review":
            self.code_review_count += 1
            if self.code_review_count == 1:
                reward = 0.0
            else:
                reward = -0.3
            summary = "code_review noted"

        elif action_type == "submit_test":
            if self.phase < 2:
                self.submit_before_phase2 = True
                reward = -1.0
                summary = "submit_test is only available in Phase 2."
                info["error"] = summary
            else:
                test_code = action.code or ""
                result = validate_test(test_code, self.working_code)
                reason = result.get("reason", "unknown")
                if result.get("accepted"):
                    reward = 3.0
                    adversarial_bonus = 3.0
                    done = True
                elif reason == "unfair_test":
                    reward = -1.0
                elif reason == "broken_logic":
                    reward = -2.0
                    oracle_penalty = -2.0
                elif reason == "too_easy":
                    reward = 0.0
                summary = f"submit_test:{reason}"
                info["validation"] = result

        else:
            summary = f"Unknown action type: {action_type}"
            info["error"] = summary

        # ── Timeout Penalty ────────────────────────────────────────────────
        if self._state.step_count >= 20 and not done:
            done = True
            reward -= 2.0
            info["timeout"] = True
            summary += " | Episode timed out"

        # ── Strategy Quality Score ─────────────────────────────────────────
        strategy_score = 0.0
        if done:
            if self.read_docs_before_first_edit:
                strategy_score += 1.0
            # ISSUE 3 FIX: only reward run_tests discipline if at least one edit happened
            if self.run_tests_after_every_edit and self.edit_count > 0:
                strategy_score += 1.0
            if not self.submit_before_phase2:
                strategy_score += 1.0
            strategy_score -= 0.5 * max(0, self.read_docs_count - 2)
            strategy_score -= 0.5 * max(0, self.edit_count - self.run_tests_count)
            strategy_score = max(0.0, strategy_score)

            if self._state.step_count < 10:
                strategy_score += 1.0
            elif self._state.step_count < 15:
                strategy_score += 0.5

        self.episode_log.append({"action": action_type, "step": self._state.step_count,
                                  "reward": reward, "summary": summary})

        obs_dict = self._build_obs_dict(summary)
        breakdown = {
            "migration_success": round(migration_success_reward, 4),
            "strategy_quality": round(strategy_score, 4),
            "adversarial_bonus": round(adversarial_bonus, 4),
            "oracle_penalty": round(oracle_penalty, 4),
            "progress_bonus": round(progress_bonus, 4)
        }
        return LegacyforgeObservation(
            **obs_dict,
            observation=obs_dict,
            reward_breakdown=breakdown,
            done=done,
            reward=round(reward, 4),
            info=info,
        )

    # -----------------------------------------------------------------------
    # Action handlers (Only keeping the logic for generating info/summary, skipping their reward)
    # -----------------------------------------------------------------------
    def _handle_read_docs(self, action):
        topic = (action.target or "routing").lower()
        cache = self._docs_cache
        if cache:
            if topic in cache:
                snippet = cache[topic]
                return 0.0, f"read_docs:{topic}", {"docs_snippet": snippet, "topic": topic, "source": "cache_exact"}
            keys = list(cache.keys())
            matches = difflib.get_close_matches(topic, keys, n=1, cutoff=0.4)
            if matches:
                best = matches[0]
                content = cache[best]
                snippet = f"[Redirected '{topic}' -> '{best}']\n\n{content}"
                return 0.0, f"read_docs:{topic}->{best}", {"docs_snippet": snippet, "topic": best, "source": "cache_fuzzy"}
            sample = list(cache.keys())[:10]
            snippet = f"Error: Topic '{topic}' not found in docs cache. Valid examples include: {sample}..."
            return 0.0, f"read_docs:{topic}:miss", {"docs_snippet": snippet, "topic": topic, "source": "cache_miss"}

        snippet = DOCS_SNIPPETS.get(topic, f"No docs found for topic '{topic}'. Valid topics: {list(DOCS_SNIPPETS)}")
        return 0.0, f"read_docs:{topic}", {"docs_snippet": snippet, "topic": topic, "source": "hardcoded"}

    def _handle_edit_function(self, action):
        name = action.target or "unknown"
        new_code = action.code or ""
        try:
            ast.parse(new_code)
        except SyntaxError as e:
            return 0.0, f"compile_error in {name}", {"error": str(e), "compile_ok": False}

        is_full_module = ("import" in new_code and ("FastAPI()" in new_code or "Flask(" in new_code or "app =" in new_code))
        if is_full_module:
            self.working_code = new_code
            return 0.0, f"edit_function:{name} (full module replaced)", {"compile_ok": True, "function": name}

        pattern = rf"(def {re.escape(name)}\s*\(.*?\):.*?)(?=\ndef |\nclass |\Z)"
        replacement_block = new_code.rstrip()
        updated = re.sub(pattern, replacement_block, self.working_code, flags=re.DOTALL)
        if updated == self.working_code and f"def {name}" not in self.working_code:
            self.working_code = self.working_code.rstrip() + "\n\n" + new_code.rstrip() + "\n"
        else:
            self.working_code = updated
        return 0.0, f"edit_function:{name} OK", {"compile_ok": True, "function": name}

    # -----------------------------------------------------------------------
    # Helpers
    # -----------------------------------------------------------------------
    def _build_obs_dict(self, summary: str) -> dict:
        return {
            "legacy_code": self.working_code,
            "docs": "Use read_docs(topic) to fetch FastAPI documentation snippets.",
            "migration_history_summary": summary,
            "level": self.current_level,
        }

    @property
    def state(self):
        return {
            "phase": self.phase,
            "test_suite_size": self.test_suite_size,
            "challenger_win_rate": self.challenger_win_rate,
            "current_level": self.current_level,
            "test_passage_rate": round(self.test_passage_rate, 4),
            "episode_log": self.episode_log,
            "read_docs_count": self.read_docs_count,
            "edit_count": self.edit_count,
            "run_tests_count": self.run_tests_count,
            "action_count": getattr(self._state, "step_count", 0),
            "passage_milestones_hit": list(self.passage_milestones_hit)
        }
